WITH RECURSIVE ECOLI_SEARCH AS (
    SELECT ID, PARENT_ID, 1 AS DEPTH
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, S.DEPTH + 1
    FROM ECOLI_DATA E
    JOIN ECOLI_SEARCH S ON E.PARENT_ID = S.ID
)

SELECT ID
FROM ECOLI_SEARCH
WHERE DEPTH = 3
ORDER BY ID