SELECT C.CAR_ID,
       C.CAR_TYPE,
       ROUND(MAX(C.DAILY_FEE) * 30 * (1 - MAX(P.DISCOUNT_RATE) / 100), 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
  ON C.CAR_TYPE = P.CAR_TYPE
 AND P.DURATION_TYPE = '30일 이상'
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
  ON C.CAR_ID = H.CAR_ID
 AND H.START_DATE <= '2022-11-30'
 AND H.END_DATE   >= '2022-11-01'
WHERE C.CAR_TYPE IN ('세단', 'SUV')
GROUP BY C.CAR_ID, C.CAR_TYPE
HAVING COUNT(H.CAR_ID) = 0
   AND ROUND(MAX(C.DAILY_FEE) * 30 * (1 - MAX(P.DISCOUNT_RATE) / 100), 0) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;